### ISSUE TITLE
project mochachai run error with upgrade zombie

### ISSUE THREAD

**Issue by screenleon** [screenleon/freeCodeCamp#3]
TypeError: browser.fill(...).pressButton is not a function at Context. (tests/2_functional-tests.js:214:12)

TypeError: browser.fill(...).pressButton is not a function at Context. (tests/2_functional-tests.js:245:12)

TypeError: browser.fill(...).pressButton is not a function at Context. (tests/2_functional-tests.js:268:12)

**Comment by screenleon** [comment]
```javascript=
browser
          .fill('', '')
          .then(() => {
            browser.pressButton('submit', function () {})
            return;
          })
```
